name: macOS

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  build-intel:
    name: OpenStarbound macOS x86_64
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.29.0

      - name: sccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{ github.job }}-Intel-${{ runner.os }}
          max-size: 250M

      - name: vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgJsonGlob: '**/source/vcpkg.json'
          vcpkgConfigurationJsonGlob: '**/source/vcpkg-configuration.json'

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/source/CMakeLists.txt'
          configurePreset: 'macos-release'
          buildPreset: 'macos-release'
          testPreset: 'macos-release'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenStarbound-macOS-Intel
          path: dist/*

  build-arm:
    name: OpenStarbound macOS arm64
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.29.2

      - name: sccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{ github.job }}-ARM-${{ runner.os }}
          max-size: 250M

      - name: vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgJsonGlob: '**/source/vcpkg.json'
          vcpkgConfigurationJsonGlob: '**/source/vcpkg-configuration.json'

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/source/CMakeLists.txt'
          configurePreset: 'macos-arm-release'
          buildPreset: 'macos-arm-release'
          testPreset: 'macos-arm-release'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenStarbound-macOS-Silicon
          path: dist/*